networks:
  mc-network:

volumes:
  mc-db-data:

services:
  frontend:
    platform: linux/amd64
    image: ${FRONTEND_IMAGE_NAME}
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_FIREBASE_SIGN_IN_URL: ${REACT_APP_FIREBASE_SIGN_IN_URL}
        REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
        REACT_APP_BACKEND_ADDRESS: ${REACT_APP_BACKEND_ADDRESS}
    restart: always
    ports:
      - "${DOCKER_HOST_FRONTEND_PORT}:80"
    networks:
      - mc-network
  db:
    image: mysql:8.0
    container_name: ${DB_NAME}
    restart: always
    volumes:
      - mc-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DOCKER_HOST_DB_SERVER_PORT}:${DB_SERVER_PORT}"
    networks:
      - mc-network
  backend:
    platform: linux/amd64
    image: ${BACKEND_IMAGE_NAME}
    depends_on:
      - db
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_HOST_BACKEND_PORT}:${BACKEND_SERVER_PORT}"
    environment:
      DB_SERVER_HOST: db
      SERVER_PORT: ${BACKEND_SERVER_PORT}
      DB_SERVER_PORT: ${DB_SERVER_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      ADMIN_LOGIN_CODE: ${ADMIN_LOGIN_CODE}
      GOOGLE_JWK_SET_URI: ${GOOGLE_JWK_SET_URI}
      RUN_TEST_PATH: ${DOCKER_CONTAINER_TEST_CASE_DIR}
    volumes:
      - ${FIREBASE_SERVICE_ACCOUNT_PATH}:/config/service-account.json:ro
      - ${DOCKER_HOST_TEST_CASE_DIR}:${DOCKER_CONTAINER_TEST_CASE_DIR}:rw
    networks:
      - mc-network