spring.application.name: meetCode

server.port: ${SERVER_PORT:8080}

# JPA configuration
spring.jpa:
  show-sql: false
  hibernate.ddl-auto: none  # Use Flyway for DB management
  properties.hibernate:
    jdbc.time_zone: Asia/Hong_Kong
    dialect: org.hibernate.dialect.MySQLDialect

spring.datasource:
  url: jdbc:mysql://${DB_SERVER_HOST}:${DB_SERVER_PORT}/${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}

# Flyway configuration
spring.flyway:
  enabled: true
  locations: classpath:db/migration

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: ${GOOGLE_JWK_SET_URI}

cors.allowed.origins: "${CORS_ALLOWED_ORIGINS}"

admin.login.code: "${ADMIN_LOGIN_CODE}"

run.test.path: "${RUN_TEST_PATH}"



